-- Found ament_cmake: 2.7.3 (/opt/ros/kilted/share/ament_cmake/cmake)
-- Found ament_lint_auto: 0.19.2 (/opt/ros/kilted/share/ament_lint_auto/cmake)
-- Found rosidl_default_generators: 1.7.1 (/opt/ros/kilted/share/rosidl_default_generators/cmake)
-- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
-- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
-- Found rosidl_adapter: 4.9.5 (/opt/ros/kilted/share/rosidl_adapter/cmake)
[31mCMake Error at /opt/ros/kilted/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:57 (message):
  execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
  boat_data_interfaces --arguments-file
  /home/ishaan/eboat_src/build/boat_data_interfaces/rosidl_adapter__arguments__boat_data_interfaces.json
  --output-dir
  /home/ishaan/eboat_src/build/boat_data_interfaces/rosidl_adapter/boat_data_interfaces
  --output-file
  /home/ishaan/eboat_src/build/boat_data_interfaces/rosidl_adapter/boat_data_interfaces.idls)
  returned error code 1:

  Traceback (most recent call last):

    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "/opt/ros/kilted/lib/python3.12/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
      main()
    File "/opt/ros/kilted/lib/python3.12/site-packages/rosidl_adapter/main.py", line 54, in main
      abs_idl_file = convert_to_idl(
                     ^^^^^^^^^^^^^^^
    File "/opt/ros/kilted/lib/python3.12/site-packages/rosidl_adapter/__init__.py", line 22, in convert_to_idl
      return convert_msg_to_idl(
             ^^^^^^^^^^^^^^^^^^^
    File "/opt/ros/kilted/lib/python3.12/site-packages/rosidl_adapter/msg/__init__.py", line 32, in convert_msg_to_idl
      msg = parse_message_string(package_name, input_file.stem, content)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/ros/kilted/lib/python3.12/site-packages/rosidl_adapter/parser.py", line 563, in parse_message_string
      msg = MessageSpecification(pkg_name, msg_name, fields, constants)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/ros/kilted/lib/python3.12/site-packages/rosidl_adapter/parser.py", line 421, in __init__
      raise ValueError(

  ValueError: the fields iterable contains duplicate names: gps_lat

Call Stack (most recent call first):
  /opt/ros/kilted/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:132 (rosidl_adapt_interfaces)
  CMakeLists.txt:29 (rosidl_generate_interfaces)

[0m
-- Configuring incomplete, errors occurred!
